### ISSUE TITLE
[Stremio 5] Black Screen and Volume Control Issues

### ISSUE THREAD

**Issue by xodexa** [Zaarrg/stremio-desktop-v5#12]
**Issue:**

- Some videos, especially anime, display only a black screen.
- Volume control is non-functional across several videos.
- In the original Stremio 5, some videos are viewable, but the volume control still doesn't work.

**Original Bug:**
- **[This bug already exists on the original Stremio, but it only grays out the volume while the video still looks normal.](https://github.com/Stremio/stremio-bugs/issues/1060)**

**Log:**

-  Black screen + Greyed Out volume
[Bad_output.txt](https://github.com/user-attachments/files/18448721/Bad_output.txt)

- Everything good
[Good_output.txt](https://github.com/user-attachments/files/18448728/Good_output.txt)

Additional Information:
- I tried recording this bug using Nvidia App. The recorded video looked fine, but the screen actually displayed a black screen.
- It seems like Nvidia gets the video output from somewhere else, as if the video is covered or out of the window.

Actually displayed (Snipping Tool):
![Image](https://github.com/user-attachments/assets/355d4e74-251c-486f-8580-8d48de7580a0)
Screenshot using Nvidia:
![Image](https://github.com/user-attachments/assets/400d1ac5-e572-4f18-aa7c-a1ec15f4e4b2)

**Comment by Zaarrg** [comment]
Okay so checked the logs and they dont have anything unusual or any errors.

Can u try adding to the `mpv.conf` located in ``%localAppData%\Programs\LNV\Stremio-5\portable_config``
One of the following lines and restarting the app and trying to play a video:

```shell
vo=gpu # Add this always normally this is set to gpu-next , maybe just gpu will be better

# Add one of the following lines
gpu-api=vulkan
gpu-api=opengl
```

**Comment by Zaarrg** [comment]
As well if that did not works its probably edge related. 
Try the following:

1. Open **Command Prompt** (cmd) and run the command `cd %localAppData%\Programs\LNV\Stremio-5\`
2. Then run the command ``set WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS=--disable-gpu``
3. Run stremio from the cmd by running `stremio.exe`

Then test if disabling the edge hardware acceleration helped.

Alternativley to the ``set WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS=--disable-gpu`` u can also try 
```shell 
set WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS=--use-angle=opengl

# Or maybe one of these will fix it
--use-angle=swiftshader
--use-angle=vulkan
--use-angle=d3d11
```

Or this one:

```shell
set WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS=--disable_direct_composition_video_overlays=1 --disable_direct_composition_sw_video_overlays=1

```

**Comment by xodexa** [comment]
Nothing seems to work, but I found out more about this weird behavior. When I watch one episode of an anime (Play in VLC option) and then click the next button in Stremio, the second episode shows up in Stremio and everything is fixed. But when I close stremio/search other anime and come back to watch, the problem reappears (black screen). This keeps happening, so I need to watch at least one episode and then click next to fix everything. Such a weird bug!

**Comment by Zaarrg** [comment]
Huh. That is indeed getting more and more weird haha. 

> When I watch one episode of an anime (Play in VLC option) and then click the next button in Stremio, the second episode shows up in Stremio and everything is fixed.

Okay so  what happens when u just click the 'Next Button' or in the bottom left corner the 'Skip' button which opens the next episode. Do you then see the video playing or still black screen ? 

Meaning i want basically to know if u HAVE to click the "Play in VLC option" for it to work. Because i have kind of a idea now of what the issue might be but if your fix only works when pressing "Play in VLC" then im not sure if my idea is correct.

Also can u try when on the video with the black screen try pressing ``F5`` to reload to page maybe that fixes it, or ``CTRL+F5`` this reloads and clears cache.

Also can u try if the above still does not work, just like u described pressing "Play in VLC" then instead of watching it in vlc just directly go back into stremio and press the "Skip" button to watch the next episode and seeing if that next episode works then.


But very good find thank you, i think i might be getting closer to knowing what the bug is.

**Comment by xodexa** [comment]
Here's what I found
Case:
1. Black screen, then F5 -> Not working.

2. Close the player from case 1, click the video again, black screen, then Ctrl + F5 -> This fixes everything, including the volume slider.

3. Close the player from case 2, click the video again, black screen, but just F5 fixes it without Ctrl + F5.

4. Close the player from case 3, click another torrent source, black screen, but just F5 fixes it now.

Looks like I just need F5, and if the problem persists, Ctrl + F5 fixes everything, including the volume slider.

"I've repeated this with 3 different anime, and the result is the same-it's repeatable."

**Comment by Zaarrg** [comment]
Okay that is very weird.

Did you try by any chance the portable version and if that has the same issue ? Cause if F5 does fix it its some kind of edge / browser issue maybe the portable version does not have it as it might be a other version that what is used by the system in general.

I would like to fix this issue in general not just u having to press F5 always so if you want we can try to identify that issue further.

**Comment by xodexa** [comment]
I'm using the portable version (with Scoop)

**Comment by Zaarrg** [comment]
scoop uses the installer, the portable version u have to download manually from the [release page](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-beta.11).

**Comment by xodexa** [comment]
Wait, so it's using my default Edge browser? By the way, I've disabled graphics acceleration by default. Nvm, I enabled graphics acceleration, but I still need to press F5.

I tried the portable version, and yep, same black screen problem—still need to press F5.

**Comment by Zaarrg** [comment]
At this point im not sure myself anymore. Checked your logs again, Checked if its maybe the web view not setting a transparent background but if that would be it u wouldn't have a backscreen but a purple screen as this is stremios default color as background.
And portable version is the same issue so its not related to your default edge runtime. 
Nvidia sees the video meaning mpv is outputting it correctly but as on the screen there is no ui shown in what Nvidia sees. Then for some reason just refreshing the page fixes it even tho to my knowledge it shouldn't as there is nothing special happening on refresh that does not happen on opening the video the first time. Its the same process.

So i will investigate this further and if i can find some reason. But as of now my best guess is its OS specific like some windows version, driver version cant correctly handle the Composting of the webview and mpv on the first time. Maybe worth trying the app on a different device. 

So i guess will probably close this issue as OS specific issue.

And for the edge browser thing. Its not using the full browser its using a part of it the WebView2 Runtime. If you have edge installed on your pc and its a recent version then it often has as part of it the WebView2 Runtime. If the app detects you have this it uses it. This allows for the app to only be 60mb as it does not have to include that runtime which is 200mb. That is why the portable version is also 200mb bigger as this has that webview2 runtime part included and does not look for a installed one. Also advantage of this you only have the webview2 runtime once on your pc minimizing the disk size used as every app that uses webview2 can use this one installed instance.

**Comment by xodexa** [comment]
I just updated to the latest **Stremio Desktop 5.0.12.** The F5 trick doesn't work anymore; it just shows a stuck purple background, and I have to reset Stremio (reopen it). If I resize the video window, I can see the video is actually there, but it's outside the visible area.

https://streamable.com/f51ext

I tried Stremio EXPERIMENTAL 5.0.13, same

**Comment by Zaarrg** [comment]
Yeah broke the f5 reload with the recent update, fixed it now again. Updated the [experimental build](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-alpha.12) u can try it now. 

This should atleast allow u to use f5 again.

**Comment by Zaarrg** [comment]
The f5 reload should now be fixed in [5.0.13](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-beta.13) release.

**Comment by xodexa** [comment]
Yep, the F5 trick works for now with **[Stremio 5.0.13 Release]**. Thanks! Let's keep hunting down this bug. I'll keep experimenting too.

**Comment by kevinization** [comment]
I have the same problem with 5.0.14, nothing seems to work for me

![Image](https://github.com/user-attachments/assets/4e3e6cf8-363f-4e03-8ae1-cbe9774e7ef1)

**Comment by Zaarrg** [comment]
@kevinization only since 5.0.14 ? Does fresh install fix it ?

**Comment by kevinization** [comment]
I have this issue in 5.0.14 and 5.0.13. Fresh install didn't fix it. I'm guessing it only happens with chapters that come from an m3u playlist. My reason to say that is that I checked it with a few .mp4 and .mkv movies and it's working fine, though I also checked it with a show that comes from a .m3u playlist and I have the black screen on it.

**Comment by HadeszxXx** [comment]
Mine was also experiencing this bug. ctrl + f5 sometimes fixes it, but sometimes it doesn't.

My guess is that it's the subtitles, because when I turn off the subtitles and press ctrl + f5 until now it's fixed, I tested it 8 times.

**Comment by kevinization** [comment]
I did turn off the subtitles and then pressed ctrl + f5, unfortunately it didn't work for me.

![Image](https://github.com/user-attachments/assets/d8baebb9-a553-4340-82ab-014ee4d3e610)

**Comment by Zaarrg** [comment]
@kevinization was this also a m3u file ? As currently i am testing it only with streams that are mp4 or mkv but cant get this same issue. 

Or maybe even better provide the file name then i can get the same file and test.

**Comment by kevinization** [comment]
I can confirm that the video I'm trying to play is from an m3u file, but I can't share it with you because I have my Stremio server self-hosted, so it can only be used on my local network. However, I can tell you that I have Torrentio installed, it's chapter 1 of the anime .hack//SIGN. 


This is the stream link (the hyperlink tool didn't work):

magnet:?xt=urn:btih:895cd6023da2a3a3deff028a792ca08e1b1dbdde&dn=Torrentio
480p&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.tracker.cl%3A1337%2Fannounce&tr=udp%3A%2F%2Fopen.stealth.si%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.torrent.eu.org%3A451%2Fannounce&tr=udp%3A%2F%2Fexplodie.org%3A6969%2Fannounce&tr=udp%3A%2F%2Fexodus.desync.com%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.ololosh.space%3A6969%2Fannounce&tr=udp%3A%2F%2Ftracker.bittor.pw%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker-udp.gbitt.info%3A80%2Fannounce&tr=udp%3A%2F%2Fopentracker.io%3A6969%2Fannounce&tr=udp%3A%2F%2Fopen.free-tracker.ga%3A6969%2Fannounce&tr=udp%3A%2F%2Fns-1.x-fins.com%3A6969%2Fannounce&tr=udp%3A%2F%2Fleet-tracker.moe%3A1337%2Fannounce&tr=udp%3A%2F%2Fisk.richardsw.club%3A6969%2Fannounce&tr=udp%3A%2F%2Fdiscord.heihachi.pw%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker810.xyz%3A11450%2Fannounce&tr=http%3A%2F%2Ftracker.xiaoduola.xyz%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.vanitycore.co%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.sbsub.com%3A2710%2Fannounce&tr=http%3A%2F%2Fnyaa.tracker.wf%3A7777%2Fannounce&tr=http%3A%2F%2Fanidex.moe%3A6969%2Fannounce&tr=http%3A%2F%2Ftracker.anirena.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.uw0.xyz%3A6969%2Fannounce&tr=http%3A%2F%2Fshare.camoe.cn%3A8080%2Fannounce&tr=http%3A%2F%2Ft.nyaatracker.com%3A80%2Fannounce&tr=895cd6023da2a3a3deff028a792ca08e1b1dbdde

**Comment by Zaarrg** [comment]
its weird. So i tested with torrentio season 1 episode 1 of .hack//SIGN. and all files are .mkv (not m3u) and they all worked with no problem. 

![Image](https://github.com/user-attachments/assets/501fb620-741f-47ba-8e52-d4da149e1e32)

Then i tested pasting the magnet link you provided directly into the Stremio search bar and it also loaded it correctly and the .mkv files could play with no issue.

So im not sure if its a file format issue. 

Do u have any subtitles plugins other then the default OpenSubtitles V3 one maybe one of those is somehow causing this ?

Also do u hear audio of the video ? Or nothing at all. 

Trying to reproduce this issue but as of now cant.

(Also tried with a iptv .m3u file and that worked as well)

Possibly this might be caused by WebView2 being broken or something, u could try deleting ``C:\Program Files (x86)\Microsoft\EdgeWebView`` then installing it again using the [webview2 installer](https://developer.microsoft.com/de-de/microsoft-edge/webview2/?ch=1&form=MA13LH#download)

But not sure if this can help as xodexa already used the portable version which has the latest webview2 included as clean install and the same issue was happening.

If this does not help then only option i can think of is getting this [debug version](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-alpha.12) of the app.

This unlocked dev tools and inspect menu and more logs when starting with ``stremio.exe > output.txt`` in console.

You can then try: Open stremio like normal, anywhere on the page ``right click > inspect`` and then going to ``console`` then on the top right click on the ``configuration wheel`` there select ``preserve log``. Same on the network tab there u can select ``preserve log`` directly at the top left.

Then after setting that up try to play the video. Then look in the Console and Network tab for anything that is marked ``red`` as error. 

Mainly in the ``console`` tab as i dont think this is a network issue. 

Then uploading a screenshot of the console error logs u get. Stuff like ``Error calling initShellComm`` is normal or ``ChromeCastTransport``. 
Also sometimes u can click on the console errors to expand them so screenshots with the expanded error would be the best.

If no errors there then running stremio via the command prompt (cmd) is only option left by using ``stremio > output.txt``

The exact steps for that would be:

1. Open **Command Prompt** (cmd) and run `cd %localAppData%\Programs\LNV\Stremio-5\`
2. Then run stremio using the `cmd stremio.exe > output.txt` . This will log what stremio and mpv are doing.
3. Reproduce the steps to the bug, e.g. Open stremio and be stuck on the splash screen.
4. Then when done close stremio fully and in the folder `%localAppData%\Programs\LNV\Stremio-5\` there now will be a **output.txt** file.
5. Upload this txt log here.

**Comment by kevinization** [comment]
I only have OpenSubtitles V3 installed.

I can hear the audio of the video.

Here's the console screenshot:

![Image](https://github.com/user-attachments/assets/61f97813-45fb-4965-bf44-5812cdbf9229)

And here's the Network screenshot (I must say that the show's thumbnails are not loading at all now, and Stremio says that my device does not suppot the stream, it only loads the first time after I install it (when it gives me the black screen failure), after that it is just like the screenshot):

![Image](https://github.com/user-attachments/assets/e4788503-4d77-4069-b1f4-a3ca5df117e1)

Here's the output.txt as well (I was not using my selfhosted server, that's why it says http://127.0.0.1/):

[output.txt](https://github.com/user-attachments/files/18484557/output.txt)

Note: Now I can't get to the point where I see the black screen and just hear the audio, because of the error I told you about above, but maybe this causes that error?

**Comment by Zaarrg** [comment]
@kevinization Does it show streaming server online ? The error is unrelated (device unsupported), it only happens when streaming server is offline. Has to be online like below:

![Image](https://github.com/user-attachments/assets/3004bf3d-c2dc-4c0c-8b30-1c095838b367)

I tested again and works fine for me the debug version so its not bugged. 

So try clearing the cache or uninstalling and remove data and then installing the debug version.

For cache clear try CTRL+F5 or deleting the stremio.exe.WebView2 folder:

![Image](https://github.com/user-attachments/assets/e9ee802b-6546-4bdd-a70a-74be33da3cf1)

Also make sure in task manager that nothing stremio releated is running like stremio-runtime, stremio or mpv. Or alternatively a pc restart closes all that as well. (Also no older stremio like v4, offical v5 or stremio service should be running )

If that still does not work try adding as streaming server:
``http://127.0.0.1:11471``
or
``http://127.0.0.1:11472``

As maybe the default 11470 port was used.

There shouldnt be any other reason why "Device unsupported" shows up.
Maybe it was only a github pages issue where the ui is hosted. 
Also test with the above mentioned local server that the app runs by default instead of the self hosted one. 

To properly find the issue we need the console / network log when the same issue is happening as before.

**Comment by kevinization** [comment]
I can confirm my streaming server is online (the official Stremio build work as expected with both local and selfhosted server). I can also confirm that this thumbnails's issue is not happening with the official Stremio build:

![Image](https://github.com/user-attachments/assets/659db970-4eaf-4bb7-9f1b-49089754e6af)

Stremio (your build) is loading the thumbnails only after I reinstall it or the first time I open it after I reboot my PC. I uninstalled it with RevoUninstaller just to make sure everything is clean now. I'm gonna test the black screen issue and put the results here. If I got the thumbnails issue again, I'll open a new issue here in GitHub.

So according to the black screen issue, here are the screenshots and the logs (I'm using the local server and it's online):

![Image](https://github.com/user-attachments/assets/57f62f36-e0d0-47a0-8cc2-dcaca9dcd0db)

Here is the Console screenshot, there's no errors (I can hear the audio is just the black screen issue):

![Image](https://github.com/user-attachments/assets/17afb9e6-cead-4303-95b1-5ceea8d4a11b)

Here is the Network screenshot, there's no errors:

![Image](https://github.com/user-attachments/assets/fb5957ec-fb84-4270-8497-79a8cc7b1c8d)

I noticed that I can see a piece of the video when I go to fullscreen and then leave it, in the bottom of the screen, here's a video:

https://github.com/user-attachments/assets/490f40bc-7c23-431c-a84e-8bea635cabd6

Here is the output.txt (I had to reinstall Stremio in order to get the right logs because once I closed it the thumbnails issue appeared again):

[output.txt](https://github.com/user-attachments/files/18494972/output.txt)

I can confirm that when I do exactly the same using the official Stremio build, everything works as expected.

**Comment by Zaarrg** [comment]
@kevinization  Thank you, this will help a lot. Will test further and see what i can find.

**Comment by Jarvis636** [comment]
Same I'm getting Black Screen from the latest version.

**Comment by Zaarrg** [comment]
> Same I'm getting Black Screen from the latest version.

@Jarvis636  Only since the latest version 5.0.14 ? Or did it work before ?

**Comment by Jarvis636** [comment]
The version 5.0 beta 16 no black screen.

**Comment by Zaarrg** [comment]
@Jarvis636 beta 16 ? there is no beta 16, beta 14 is the latest (5.0.14). Also what exact version u mean by stable version ?

**Comment by Jarvis636** [comment]
Beta 14 sorry,I revert to the beta version 5.0 from stremio.com/downloads no black screen.

**Comment by Jarvis636** [comment]
But I have to say even with the black screen on 5.0.14 its a lot faster and smoother than 5.0 good job hopefully that black screen issue is resolved.

**Comment by Zaarrg** [comment]
@Jarvis636 

If you don't mind could you try [this](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-alpha.12) version ([Direct-Link](https://github.com/Zaarrg/stremio-desktop-v5/releases/download/5.0.0-alpha.12/Stremio.5.0.14-x64-potential-blackscreen-fix.exe)) of the app the ``Stremio.5.0.14-x64-potential-blackscreen-fix.exe``. I rewrote the webview2 transport which communicates between web and app and its now pretty close to the official stremio v5 so maybe this fixes the issue, not sure though.

**Comment by neura-neura** [comment]
I did try the `Stremio.5.0.14-x64-potential-blackscreen-fix.exe` but the black screen is still there, with the same behavior as before:

![Image](https://github.com/user-attachments/assets/9646aad7-e2d3-4104-b144-482114374489)

**Comment by Zaarrg** [comment]
@neura-neura thnx. Hm i see. Well i have one more idea why this might  be happening. So can u try the ``Stremio 5.0.14-x64-potential-blackscreen-fix2.exe`` ([Release Tab](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-alpha.12), [Direct-Link](https://github.com/Zaarrg/stremio-desktop-v5/releases/download/5.0.0-alpha.12/Stremio.5.0.14-x64-potential-blackscreen-fix2.exe))  this now uses the official unmodified ui from ``https://web.stremio.com/``  and i suspect its something with the ui as the volume slider is disabled and others saw the video behind the black screen.

U might need to start the app twice as i was stuck on first start on the splash screen and then closed started again and it then worked.

(Sadly cant reproduce this issue, tried on multiple systems and everything works fine for me, so its quite hard to debug)

**Comment by neura-neura** [comment]
The `Stremio 5.0.14-x64-potential-blackscreen-fix2.exe` has no black screen! Embeded subs are also working

![Image](https://github.com/user-attachments/assets/618861a7-1bbf-4f2b-b675-bb736b608bd6)

**Comment by Zaarrg** [comment]
That is actually amazing. Thank you very much for the help. I assume volume slider also works ? 

So now will apply the fixes like vertical subtitle alignment, direct addon install, local file playback and more to that official stremio version and hopefully it will still work. So there will be one more experimental version that needs to be tested and this might actually be fixed for good.

**Comment by neura-neura** [comment]
Volume slider is not working, it looks behind, so when I try to use it nothing happens

**Comment by Zaarrg** [comment]
I see. So u can still drag the slider but it does nothing ? Or is dragging / adjusting it not possible as well ? 
Cause if adjusting it is possible and just nothing happens then i think i know what the bug is.

**Comment by neura-neura** [comment]
Dragging/adjusting is not possible at all

**Comment by Zaarrg** [comment]
Alr, did you test by any chance if adjusting using arrow key up or down works to adjust volume?

**Comment by neura-neura** [comment]
The arrow keys up and down are not working to adjust the volume. Only when I click mute/unmute with the mouse the volume changes. Anything else is not working.

**Comment by Zaarrg** [comment]
@neura-neura 

Okay so investigated a bit and i might know why the slider is disabled but i would need some logs to confirm the exact issue.

Can u try the following:
1. Get the [Stremio.5.0.14-x64-potential-blackscreen-fix3-debug.exe](https://github.com/Zaarrg/stremio-desktop-v5/releases/download/5.0.0-alpha.12/Stremio.5.0.14-x64-potential-blackscreen-fix3-debug.exe)
2. Open stremio play any video where that issue is.
2.1. (Mabye its even fixed already as i added a possible fix as well)
3. **Right Click** > **Inspect** then navigate to **Console** tab
4. Then in the console type in ``allow pasting``

Then copy paste and press enter the following snippet:
```shell
(() => {
  // Find the VolumeSlider component
  const slider = document.querySelector('[class*="volume-slider"]');
  if (!slider) return console.error('Slider not found');

  // Access React internals
  const fiberKey = Object.keys(slider).find(k => k.startsWith('__reactFiber$'));
  let fiber = slider[fiberKey];
  let targetFiber = null;

  // Traverse to find component with volume prop
  while (fiber) {
    if (fiber?.memoizedProps?.volume !== undefined) {
      targetFiber = fiber;
      break;
    }
    fiber = fiber.return;
  }

  if (!targetFiber) return console.error('Component not found');

  // Log original values
  const props = targetFiber.memoizedProps;
  console.log('Current volume:', props.volume);
  console.log('Disabled state:', props.volume === null || isNaN(props.volume));
  console.log('Current volume:', props.volume);
  console.log('Disabled calculated as:', props.volume === null || isNaN(props.volume));
  console.log('Raw values:', {
     volume: props.volume,
     isNull: props.volume === null,
     isNaN: isNaN(props.volume)
  });

  // Force update mechanism
  const forceUpdate = () => {
    try {
      // Method 1: Use React's internal scheduler
      const root = targetFiber._debugOwner || targetFiber;
      const updater = root?.updateQueue || root?.memoizedState?.updateQueue;
      if (updater) {
        updater.isForceUpdate = true;
        React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentDispatcher.current.forceUpdate();
      }
    } catch (e) {
      // Method 2: Alternative update trigger
      const fakeEvent = new Event('resize');
      window.dispatchEvent(fakeEvent);
      console.log('Fallback update triggered');
    }
  };

  // Hijack the component's disabled calculation
  const originalType = targetFiber.type;
  targetFiber.type = function HijackedComponent(props) {
    const result = originalType(props);
    return {
      ...result,
      props: {
        ...result.props,
        disabled: false // Force disabled to false
      }
    };
  };

  // Trigger update
  forceUpdate();
  console.log('Disabled state overridden to false');
})();
```

This should log all the raw values i need to see why the volume slider is even disabled in the first place and also this should force the slider to be enabled again. It might take a second until it updates the slider to be enabled again. You can try playing the video for a second or so the slider should then update to be enabled again.

Then u should be able to click on the slider to adjust volume. This is only for testing to see if the volume setting functionality still works. Or if this is also broken. 

This will be buggy as when i tested i could only click not drag and also it did not update visually the slider but i could hear that the volume changed.

The process will look something like this:

https://github.com/user-attachments/assets/d4fd5838-30db-4a5f-944c-2ee70f96b853

edit: (Seems like my obs settings are kinda rip, but should still be illustrative enough)

**Comment by Jarvis636** [comment]
Its fixed I didn't had to copy and paste

**Comment by neura-neura** [comment]
Here are the results, it's working as expected.

https://github.com/user-attachments/assets/2bce152e-84f7-4485-9fe6-427c6be0f5df

![Image](https://github.com/user-attachments/assets/f2e3f546-4169-45c0-b63c-cdedd3afaea6)

**Comment by Zaarrg** [comment]
@neura-neura / @Jarvis636  Thank you a lot that helped. So now it should be fixed. Made a release build this now has all the features like normal. Can u check if it still is fixed as i would like to prevent pushing this as new version and it not being fixed anymore for you. [Stremio.5.0.14-x64-release-candidate.exe](https://github.com/Zaarrg/stremio-desktop-v5/releases/download/5.0.0-alpha.12/Stremio.5.0.14-x64-release-candidate.exe)

**Comment by MochiVN634** [comment]
@Zaarrg I was having the same black screen + unusable volume control issue too, I tried this build you sent us, the volume control can now be used, however, the black screen problem persists and the only way to fix it is by pressing F5 to reload the content.

Edit: Actually, I could only adjust the volume the first time I tried to play an anime episode, but after trying again, it's unusable again. Both the black screen and the volume can only be fixed by pressing F5.

**Comment by Jarvis636** [comment]
@Zaarrg tested the release candidate I'm back the black screen but the volume control slider is working.

**Comment by Zaarrg** [comment]
@MochiVN634 @Jarvis636  I see, sry to ask u so often to test but just cant get that issue on my systems to test myself and pin point the exact issue. Can u check now again, updated the web ui with what i think was the issue.
U will need to delete ``%localAppData%\Programs\LNV\Stremio-5\stremio.exe.WebView2`` and login in again. 
This allows the cache to refresh and also guarantee it the latest web ui version and not something cached.

**Comment by Jarvis636** [comment]
@Zaarrg deleted %localAppData%\Programs\LNV\Stremio-5\stremio.exe.WebView2 relog in, still getting the black screen.

**Comment by MochiVN634** [comment]
@Zaarrg tried deleting the folder you mentioned, unfortunately, the issue persists.

**Comment by YuriSabbath** [comment]
> [@Zaarrg](https://github.com/Zaarrg) deleted %localAppData%\Programs\LNV\Stremio-5\stremio.exe.WebView2 relog in, still getting the black screen.

same here, the earlier version fixed the issue, but now that a I installed the realease candidate it happens again!

**Comment by Zaarrg** [comment]
Okay so made more changes try this version now:
[Stremio.5.0.14-x64-blackscreen-4.exe](https://github.com/Zaarrg/stremio-desktop-v5/releases/download/5.0.0-alpha.12/Stremio.5.0.14-x64-blackscreen-4.exe)

edit: (Or just delete the cache ``%localAppData%\Programs\LNV\Stremio-5\stremio.exe.WebView2`` anyway to make sure the ui is latest version as changed something there as well now)

You might need to delete that cache folder again or start twice if stuck on splash screen. 
And if that does not work just to confirm if the issue is with the web version im using do:
1. Go to ``%localAppData%\Programs\LNV\Stremio-5\``
2. Right click `Open in terminal` or alternativly to step 1 and to 2: Open **cmd** and paste 
``cd %localAppData%\Programs\LNV\Stremio-5\``
3. then start stremio with:
```
stremio.exe --webui-url=https://web.stremio.com/
```

**Comment by Jarvis636** [comment]
Its working no black screen and volume slider is working just needed to delete %localAppData%\Programs\LNV\Stremio-5\stremio.exe.WebView2 once and religion.

**Comment by Zaarrg** [comment]
@Jarvis636 Amazing! [5.0.15](https://github.com/Zaarrg/stremio-desktop-v5/releases) should then also work as its exactly the same version as the ``blackscreen-4`` one + bunch of other stuff (Listed in changelog)

**Comment by neura-neura** [comment]
I just tried the 5.0.15 and everything is working as expected, thanks a lot. By any chance, can we have an experimental version of the 5.0.15 with the devtools unlocked as well? I want to work on some extensions and it'd be helpful if I can check the console and everything.

**Comment by neura-neura** [comment]
Oh, the volume slider bar is blocked again with the 5.0.15, I didn't see it, it happened (I guess) after i went to full screen and went back to normal.

https://github.com/user-attachments/assets/1aabbd1e-8f99-4d72-be9f-1bd909c28ec2


EDIT: I didn't delete anything, I just went from [Stremio.5.0.14-x64-potential-blackscreen-fix3-debug.exe](https://github.com/Zaarrg/stremio-desktop-v5/releases/download/5.0.0-alpha.12/Stremio.5.0.14-x64-potential-blackscreen-fix3-debug.exe) to [5.0.15](https://github.com/Zaarrg/stremio-desktop-v5/releases) without delete anything. Does that could be the issue?

**Comment by Zaarrg** [comment]
@neura-neura 

>  By any chance, can we have an experimental version of the 5.0.15 with the devtools unlocked as well?

Added to the 5.0.15 [release](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-beta.15) a debug version ``Stremio.5.0.15-x64-debug.exe``.

> EDIT: I didn't delete anything, I just went from [Stremio.5.0.14-x64-potential-blackscreen-fix3-debug.exe](https://github.com/Zaarrg/stremio-desktop-v5/releases/download/5.0.0-alpha.12/Stremio.5.0.14-x64-potential-blackscreen-fix3-debug.exe) to [5.0.15](https://github.com/Zaarrg/stremio-desktop-v5/releases) without delete anything. Does that could be the issue?

Can u try now again added a other fix to the web ui and also try with deleting the cache folder ``%localAppData%\Programs\LNV\Stremio-5\stremio.exe.WebView2`` or before deleting anything maybe just doing ``CTRL+F5`` will be enough.

**Comment by neura-neura** [comment]
I just tried the `Stremio.5.0.15-x64-debug.exe` and now everything is working as expected, I didn't need to delete the cache folder or press CTRL + F5,  I just replaced the version. Thank you

**Comment by Zaarrg** [comment]
Nice, probably the web ui fix i pushed. When running the installer it also deletes cache automatically else users would need to delete on each version update the cache manually for all web ui changes to apply. So by u just running the ``Stremio.5.0.15-x64-debug.exe`` it also did the same as deleting that cache folder.

**Comment by MochiVN634** [comment]
@Zaarrg Hi, I just installed version 5.0.15, and while yes, the black screen bug was fixed, sometimes the entire app stops responding to any commands, like, my anime episode continued playing, but I couldn't pause it, nor go back to Stremio main menu, I was going to try restarting it, but now I'm getting stucked on the loading screen.
Also, is it normal for the Statistics button in the player to show 0 peers and 0MB/s download speed?

**Comment by Zaarrg** [comment]
@MochiVN634 thats weird will check if i can find what might be causing this. Did you try deleting the ``%localAppData%\Programs\LNV\Stremio-5\stremio.exe.WebView2`` cache folder and see if that fixes it in the long term. Also should fix the stuck on load screen. 

The network statistic is normal when using debrid services. It only works when playing torrents directly as those also have peers and all while the links u get from the cached debrid services are just stream / download links, so no statistics there.

And also it only shows statistics if playing using stremio server but normaly most content is played via mpv.

**Comment by MochiVN634** [comment]
@Zaarrg Before installing the version 5.0.15 for the first time, I did a complete uninstall of the previous version, even deleting any Stremio related folder I could find in %localAppData%, that's why I find very weird that this bug occurred, then I tried deleting the stremio.exe.WebView2 folder and restarting Stremio, tested for about 10 minutes and couldn't replicate the error anymore, I'll be watching anime for some hours today and report if I find any problem, thank you in advance!

**Comment by Zaarrg** [comment]
Yeah its weird, it seems keeping the ``stremio.exe.WebView2`` folder just causes bunch of issues in general. Will be checking if there is some better solution as the only reason its kept is to not lose the user data as otherwise on update always login would be needed.

**Comment by MochiVN634** [comment]
@Zaarrg I just managed to replicate the bug after watching an anime episode, the problem occurred after the episode finished, and the autoplay started the second episode automatically. The only thing I can do when this happens is closing Stremio entirely from system tray (Just closing it pressing the X button and reopening it via the system tray doesn't fix the issue).

And now when I try to open Stremio again, it gets stuck on the loading screen, and the only way to fix it is deleting that stremio.exe.WebView2 folder.

**Comment by Zaarrg** [comment]
Will be checking what it might be.

**Comment by MochiVN634** [comment]
Today I was going to watch some anime but Stremio got stuck on the loading screen again.

**Comment by neura-neura** [comment]
I have never stopped being stuck in the loading screen, it has always happened, but I guess we should open a new issue for that.

**Comment by Zaarrg** [comment]
Yeah the loading screen is also a known issue for a while now. Working on fixing that + this weird unresponsive app issue now.

**Comment by Zaarrg** [comment]
@MochiVN634 @neura-neura 

Could u check if this version and if it fixes the issues for you. [Stremio.5.0.15-x64-loading-stuck-fix-and-other.exe](https://github.com/Zaarrg/stremio-desktop-v5/releases/download/5.0.0-alpha.12/Stremio.5.0.15-x64-loading-stuck-fix-and-other.exe)

This version should fix the stuck on splash screen. Tested this version as portable version, spam opened it ~80 times and didnt get stuck a single time. Only potentially first boot might take longer or get stuck because of cache and only way to fix is restart app.

And this should potentially also for MochiVN634 fix the app being unresponsive after autoplay of next episode as added some fixes to the web ui that i think might have caused this. You can test by opening one episode then skipping to like 10 secs before end of episode and wait for auto play of next episode.

**Comment by MochiVN634** [comment]
@Zaarrg Well, the app becoming unresponsive was an issue that was hard to replicate. It only happened about 2 or 3 times. At least, I tried skipping 3 episodes in a row on the build you sent us and couldn't replicate it, so I guess it's fixed! The first time I opened Stremio, it did take quite a while to get past the loading screen (I'm pretty sure it was about 15 seconds or even more). So, it would be great if it could take even less time to build the cache, and of course, prevent that rare chance of getting stuck the first time, but those are only enhancement suggestions. Thank you very much for fixing all these bugs!

**Comment by Zaarrg** [comment]
For now will close this issue as all fixes are now in [5.0.16](https://github.com/Zaarrg/stremio-desktop-v5/releases/tag/5.0.0-beta.16) and it should therefore be fixed.

If still happens this can be reopened
