### ISSUE TITLE
Windows 11: Fullscreen button does not work

### ISSUE THREAD

**Issue by beimingyouyu62510** [Zaarrg/stremio-desktop-v5#149]
**Title:** Windows 11: Fullscreen button does not work (single monitor)

---

### Description
On Windows 11 (single monitor setup), the fullscreen button does nothing.  
No crash occurs, but the player window does not enter fullscreen.  

- App: Stremio Community v5 (latest release)  
- OS: Windows 11  
- Display setup: Single monitor  
- Tested with `f`, `Alt+Enter`, `F11` → none of them work.  
- Tried editing `mpv.conf` (e.g., `fullscreen=yes`), but the issue persists.  
- mpv itself works fine when run standalone, so the problem seems to be the **UI → mpv fullscreen event not being passed**.

---

### Steps to reproduce
1. Open Stremio Community v5 on Windows 11 (single monitor)  
2. Play any video  
3. Click the fullscreen button (or press `f`)  

---

### Expected behavior
The player should enter fullscreen mode.  

---

### Actual behavior
Nothing happens. No crash, no errors, just no fullscreen.  

---

### Additional notes
- This issue occurs even with the default `mpv.conf`.  
- Tested on the latest release build.  
- Possibly related to WebView2 → mpv window handling on Windows 11.  

---

**Comment by Zaarrg** [comment]
what version does it show for u on the settings page in the bottom left corner ?

It should match this:

<img width="289" height="146" alt="Image" src="https://github.com/user-attachments/assets/f416bdd8-b4f2-43ab-871c-2eb11c212bd1" />

if not press `CTRL+F5` to refresh.

As the `f` key was just fixed yesterday.

Edit*: Not entirely sure but cant get that behavior/bug on my systems, checked on my pc and laptop both win11 with version 5.0.0-beta.26.40 and f key and fullscreen button work.

**Comment by beimingyouyu62510** [comment]
<img width="814" height="295" alt="Image" src="https://github.com/user-attachments/assets/d22e5e59-0ad7-433f-b661-4e54f1b0fc7b" />Refreshing with CTRL+F5 didn't change anything; the issue persists. I'm not sure where the problem lies, but the official version works fine.

**Comment by Zaarrg** [comment]
@beimingyouyu62510 

Are u sure u are on the correct Stremio build and are on the [Stremio Community V5](https://github.com/Zaarrg/stremio-community-v5/releases) version ? Cause in the settings menu there is no build version, the build version is only on the offical stremio desktop client. This github is for the community build.

Your settings version should exactly match the one on my screenshot and there should not be a build version. The build version suggest that its loading the ui from the offical stremio `https://web.stremio.com/` and not like it should from `https://stremio.zarg.me/`

If u are certain u are on the correct client then check `%localAppData%\Programs\LNV\Stremio-5` and delete the `stremio.exe.WebView2` folder and then start the app again. (To delete it u have to close the app)

Also check if this link `https://stremio.zarg.me/` is reachable in ur browser and does not get blocked.

If the above does not help uninstall the app fully and install it via the installer again from [Stremio Community V5](https://github.com/Zaarrg/stremio-community-v5/releases)

And if even this does not help visit `%localAppData%\Programs\LNV\Stremio-5`. Then right click `stremio.exe` then click `Create Shortcut`.

Then right click on the shortcut and click properties and add in the target line the following to the end: `--webui-url=https://stremio.zarg.me/`

So the whole Target: line will look something like this `...\AppData\Local\Programs\LNV\Stremio-5\stremio.exe --webui-url=https://stremio.zarg.me/`

But for this step to work u have to make sure u are on the correct [Stremio Community V5](https://github.com/Zaarrg/stremio-community-v5/releases) desktop client.

(So if u are certain u are on the correct client it first trys to load https://stremio.zarg.me/ then fallback 1: https://zaarrg.github.io/stremio-web-shell-fixes/ and then fallback 2 which is the offical one and does not include community fixes and featuers: https://web.stremio.com/)

Edit: And also when it loads the offical web.stremio i dont think `CTRL+F5` works as this is also a community version feature to allow refreshing the page fully.
